import { useState, useCallback } from 'react';
import { MoleculeBackground } from '@/components/MoleculeBackground';
import { ResearchForm } from '@/components/ResearchForm';
import { ProgressBar } from '@/components/ProgressBar';
import { ResultsPanel } from '@/components/ResultsPanel';
import { toast } from '@/hooks/use-toast';

type AppState = 'idle' | 'loading' | 'complete';

// Mock output content (simulates output.txt content)
const mockOutputContent = `# Pharmaceutical Research Report

## Executive Summary
Comprehensive multi-agent analysis of the requested pharmaceutical molecule.

## Market Intelligence (IQVIA Analysis)
- Global market size and growth projections
- Regional market dynamics
- Competitive landscape analysis

## Patent Landscape
- Active patents and expiry timelines
- Freedom-to-operate assessment
- IP strategy recommendations

## Clinical Research Overview
- Ongoing clinical trials
- Efficacy and safety profiles
- Pipeline developments

## Regulatory Intelligence
- Approval status across regions
- Regulatory pathway recommendations
- Compliance requirements

## Competitive Analysis
- Key market players
- Product portfolio comparison
- Strategic positioning

## Conclusions & Recommendations
Based on the comprehensive analysis, strategic recommendations for market entry and development.

---
*Report generated by Pharmaceutical Multi-Agent Research System*
`;

const Index = () => {
  const [appState, setAppState] = useState<AppState>('idle');
  const [moleculeName, setMoleculeName] = useState('');

  const handleSubmit = useCallback((name: string) => {
    setMoleculeName(name);
    setAppState('loading');
    toast({
      title: "Research Started",
      description: `Analyzing ${name} with multi-agent system...`,
    });
  }, []);

  const handleComplete = useCallback(() => {
    setAppState('complete');
    toast({
      title: "Analysis Complete",
      description: "Your research report is ready for download.",
    });
  }, []);

  const handleDownload = useCallback(() => {
    // Convert markdown to basic HTML for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Research Report - ${moleculeName}</title>
        <style>
          body { font-family: 'Helvetica', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; }
          h1 { color: #1a1a2e; border-bottom: 2px solid #16b8a7; padding-bottom: 10px; }
          h2 { color: #334155; margin-top: 30px; }
          ul { padding-left: 20px; }
          li { margin: 8px 0; }
          hr { margin: 30px 0; border: none; border-top: 1px solid #e2e8f0; }
          em { color: #64748b; }
        </style>
      </head>
      <body>
        <h1>Research Report: ${moleculeName}</h1>
        ${mockOutputContent
          .replace(/^# (.+)$/gm, '<h1>$1</h1>')
          .replace(/^## (.+)$/gm, '<h2>$1</h2>')
          .replace(/^- (.+)$/gm, '<li>$1</li>')
          .replace(/(<li>.*<\/li>\n)+/g, '<ul>$&</ul>')
          .replace(/\*(.+)\*/g, '<em>$1</em>')
          .replace(/---/g, '<hr>')
          .replace(/\n\n/g, '<br><br>')}
      </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${moleculeName.toLowerCase().replace(/\s+/g, '-')}-research-report.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Open the HTML file in your browser and print to PDF.",
    });
  }, [moleculeName]);

  const handleNewSearch = useCallback(() => {
    setAppState('idle');
    setMoleculeName('');
  }, []);

  return (
    <div className="relative min-h-screen bg-background overflow-hidden">
      {/* Animated background */}
      <MoleculeBackground />

      {/* Gradient overlays */}
      <div className="fixed inset-0 bg-gradient-to-b from-background via-transparent to-background pointer-events-none" />
      <div className="fixed inset-0 bg-gradient-to-r from-primary/5 via-transparent to-accent/5 pointer-events-none" />

      {/* Main content */}
      <main className="relative z-10 min-h-screen flex flex-col items-center justify-center px-4 py-12">
        {appState === 'idle' && (
          <ResearchForm onSubmit={handleSubmit} isLoading={false} />
        )}

        {appState === 'loading' && (
          <div className="w-full space-y-8">
            <div className="text-center mb-8">
              <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground mb-2">
                Analyzing <span className="text-primary">{moleculeName}</span>
              </h2>
              <p className="text-muted-foreground">
                Multi-agent research in progress. This may take 10-15 minutes.
              </p>
            </div>
            <ProgressBar
              isActive={true}
              duration={15000} // 15 seconds for demo, change to 900000 for 15 min
              onComplete={handleComplete}
            />
          </div>
        )}

        {appState === 'complete' && (
          <ResultsPanel
            moleculeName={moleculeName}
            onDownload={handleDownload}
            onNewSearch={handleNewSearch}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="relative z-10 text-center py-6 text-sm text-muted-foreground">
        <p>Pharmaceutical Multi-Agent Research System</p>
      </footer>
    </div>
  );
};

export default Index;
