import { useState, useCallback, useEffect, useRef } from 'react';
import { MoleculeBackground } from '@/components/MoleculeBackground';
import { ResearchForm } from '@/components/ResearchForm';
import { ProgressBar } from '@/components/ProgressBar';
import { ResultsPanel } from '@/components/ResultsPanel';
import { toast } from '@/hooks/use-toast';
import { startResearch, getResearchStatus, checkHealth } from '@/lib/api';

type AppState = 'idle' | 'loading' | 'complete';

const Index = () => {
  const [appState, setAppState] = useState<AppState>('idle');
  const [moleculeName, setMoleculeName] = useState('');
  const [reportContent, setReportContent] = useState('');
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const [backendConnected, setBackendConnected] = useState<boolean | null>(null);
  const jobIdRef = useRef<string | null>(null);
  const pollingRef = useRef<NodeJS.Timeout | null>(null);

  // Check backend connection on mount
  useEffect(() => {
    checkHealth().then(setBackendConnected);
  }, []);

  // Cleanup polling on unmount
  useEffect(() => {
    return () => {
      if (pollingRef.current) {
        clearInterval(pollingRef.current);
      }
    };
  }, []);

  const pollStatus = useCallback(async () => {
    if (!jobIdRef.current) return;

    try {
      const status = await getResearchStatus(jobIdRef.current);
      setElapsedSeconds(status.elapsed_seconds);

      if (status.status === 'complete' && status.result) {
        // Stop polling
        if (pollingRef.current) {
          clearInterval(pollingRef.current);
          pollingRef.current = null;
        }
        
        setReportContent(status.result);
        setAppState('complete');
        toast({
          title: "Analysis Complete",
          description: "Your research report is ready for download.",
        });
      } else if (status.status === 'error') {
        // Stop polling
        if (pollingRef.current) {
          clearInterval(pollingRef.current);
          pollingRef.current = null;
        }
        
        setAppState('idle');
        toast({
          title: "Research Error",
          description: status.error || "An error occurred during research.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error('Error polling status:', error);
    }
  }, []);

  const handleSubmit = useCallback(async (name: string) => {
    setMoleculeName(name);
    setAppState('loading');
    setElapsedSeconds(0);

    // Check if backend is connected
    const isConnected = await checkHealth();
    setBackendConnected(isConnected);

    if (!isConnected) {
      // Demo mode - simulate with timeout
      toast({
        title: "Demo Mode",
        description: `Backend not connected. Simulating research for ${name}...`,
      });
      
      // Simulate completion after 15 seconds for demo
      setTimeout(() => {
        setReportContent(`# Pharmaceutical Research Report: ${name}

## Executive Summary
Comprehensive multi-agent analysis of ${name}.

## Market Intelligence (IQVIA Analysis)
- Global market size and growth projections
- Regional market dynamics
- Competitive landscape analysis

## Patent Landscape
- Active patents and expiry timelines
- Freedom-to-operate assessment
- IP strategy recommendations

## Clinical Research Overview
- Ongoing clinical trials
- Efficacy and safety profiles
- Pipeline developments

## Regulatory Intelligence
- Approval status across regions
- Regulatory pathway recommendations
- Compliance requirements

## Competitive Analysis
- Key market players
- Product portfolio comparison
- Strategic positioning

## Conclusions & Recommendations
Based on the comprehensive analysis, strategic recommendations for market entry and development.

---
*Report generated by Pharmaceutical Multi-Agent Research System*
*Note: This is demo content. Connect to the backend for real research.*
`);
        setAppState('complete');
        toast({
          title: "Analysis Complete (Demo)",
          description: "Demo report is ready for download.",
        });
      }, 15000);
      
      return;
    }

    try {
      const response = await startResearch(name);
      jobIdRef.current = response.job_id;
      
      toast({
        title: "Research Started",
        description: `Analyzing ${name} with multi-agent system...`,
      });

      // Start polling for status every 10 seconds
      pollingRef.current = setInterval(pollStatus, 10000);
      // Also poll immediately after a short delay
      setTimeout(pollStatus, 2000);
    } catch (error) {
      console.error('Error starting research:', error);
      setAppState('idle');
      toast({
        title: "Error",
        description: error instanceof Error ? error.message : "Failed to start research",
        variant: "destructive",
      });
    }
  }, [pollStatus]);

  const handleComplete = useCallback(() => {
    // This is called by ProgressBar in demo mode
    // In real mode, completion is handled by polling
  }, []);

  const handleDownload = useCallback(() => {
    // Convert markdown to HTML for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Research Report - ${moleculeName}</title>
        <style>
          body { font-family: 'Helvetica', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; }
          h1 { color: #1a1a2e; border-bottom: 2px solid #16b8a7; padding-bottom: 10px; }
          h2 { color: #334155; margin-top: 30px; }
          h3 { color: #475569; margin-top: 20px; }
          ul, ol { padding-left: 20px; }
          li { margin: 8px 0; }
          hr { margin: 30px 0; border: none; border-top: 1px solid #e2e8f0; }
          em { color: #64748b; }
          table { border-collapse: collapse; width: 100%; margin: 20px 0; }
          th, td { border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
          th { background: #f8fafc; }
          pre { background: #f8fafc; padding: 15px; border-radius: 5px; overflow-x: auto; }
          code { background: #f1f5f9; padding: 2px 5px; border-radius: 3px; }
        </style>
      </head>
      <body>
        <h1>Research Report: ${moleculeName}</h1>
        ${reportContent
          .replace(/^### (.+)$/gm, '<h3>$1</h3>')
          .replace(/^## (.+)$/gm, '<h2>$1</h2>')
          .replace(/^# (.+)$/gm, '<h1>$1</h1>')
          .replace(/^\* (.+)$/gm, '<li>$1</li>')
          .replace(/^- (.+)$/gm, '<li>$1</li>')
          .replace(/^\d+\. (.+)$/gm, '<li>$1</li>')
          .replace(/(<li>.*<\/li>\n)+/g, '<ul>$&</ul>')
          .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
          .replace(/\*(.+?)\*/g, '<em>$1</em>')
          .replace(/`(.+?)`/g, '<code>$1</code>')
          .replace(/---/g, '<hr>')
          .replace(/\n\n/g, '</p><p>')}
      </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${moleculeName.toLowerCase().replace(/\s+/g, '-')}-research-report.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Open the HTML file in your browser and print to PDF.",
    });
  }, [moleculeName, reportContent]);

  const handleNewSearch = useCallback(() => {
    // Stop any ongoing polling
    if (pollingRef.current) {
      clearInterval(pollingRef.current);
      pollingRef.current = null;
    }
    jobIdRef.current = null;
    
    setAppState('idle');
    setMoleculeName('');
    setReportContent('');
    setElapsedSeconds(0);
  }, []);

  return (
    <div className="relative min-h-screen bg-background overflow-hidden">
      {/* Animated background */}
      <MoleculeBackground />

      {/* Gradient overlays */}
      <div className="fixed inset-0 bg-gradient-to-b from-background via-transparent to-background pointer-events-none" />
      <div className="fixed inset-0 bg-gradient-to-r from-primary/5 via-transparent to-accent/5 pointer-events-none" />

      {/* Backend status indicator */}
      {backendConnected !== null && (
        <div className="fixed top-4 right-4 z-50">
          <div className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-xs font-medium ${
            backendConnected 
              ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30' 
              : 'bg-amber-500/20 text-amber-400 border border-amber-500/30'
          }`}>
            <div className={`w-2 h-2 rounded-full ${backendConnected ? 'bg-emerald-400' : 'bg-amber-400'} animate-pulse`} />
            {backendConnected ? 'Backend Connected' : 'Demo Mode'}
          </div>
        </div>
      )}

      {/* Main content */}
      <main className="relative z-10 min-h-screen flex flex-col items-center justify-center px-4 py-12">
        {appState === 'idle' && (
          <ResearchForm onSubmit={handleSubmit} isLoading={false} />
        )}

        {appState === 'loading' && (
          <div className="w-full space-y-8">
            <div className="text-center mb-8">
              <h2 className="font-display text-2xl md:text-3xl font-bold text-foreground mb-2">
                Analyzing <span className="text-primary">{moleculeName}</span>
              </h2>
              <p className="text-muted-foreground">
                Multi-agent research in progress. This may take 10-15 minutes.
              </p>
              {elapsedSeconds > 0 && (
                <p className="text-sm text-muted-foreground mt-2">
                  Elapsed: {Math.floor(elapsedSeconds / 60)}m {elapsedSeconds % 60}s
                </p>
              )}
            </div>
            <ProgressBar
              isActive={true}
              duration={backendConnected ? 900000 : 15000} // 15 min for real, 15 sec for demo
              onComplete={handleComplete}
            />
          </div>
        )}

        {appState === 'complete' && (
          <ResultsPanel
            moleculeName={moleculeName}
            onDownload={handleDownload}
            onNewSearch={handleNewSearch}
          />
        )}
      </main>

      {/* Footer */}
      <footer className="relative z-10 text-center py-6 text-sm text-muted-foreground">
        <p>Pharmaceutical Multi-Agent Research System</p>
      </footer>
    </div>
  );
};

export default Index;
